services:
  mysql:
    image: mysql:latest
    container_name: scrumgame
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/java/org/scrumgame/database/tables/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - scrumgame-network
    restart: always


volumes:
  mysql_data:

networks:
  scrumgame-network:
    driver: bridge