version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: chauffeursync-db-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - chauffeursync-network
    restart: always

networks:
  chauffeursync-network:
    driver: bridge
